branch-defaults:
  master:
    environment: dncash-io-instant-cash-dev
environment-defaults:
  dncash-io-instant-cash-dev:
    branch: null
    repository: null
global:
  application_name: dncash-io
  branch: null
  default_ec2_keyname: null
  default_platform: node.js
  default_region: eu-central-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
